### PR TITLE
.travis.yml update: fh-build, MongoDB service

### PR DESCRIPTION
**Pull request by psturc**

### CODE REVIEW

**Comment by odra** [comment]
After a bit of testing, the error is being generated by fh-npm (which is executed by fh-build), not really sure why, but it seems to be an issue with the gyp bidings:

```
gyp: /home/lrossetti/.node-gyp/0.10.45/common.gypi not found (cwd: /home/lrossetti/fh-templates/fh-mbaas-service/node_modules/fh-mbaas-api/node_modules/fh-mbaas-client/node_modules/bunyan/node_modules/dtrace-provider) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/lrossetti/.nvm/v0.10.45/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.5.7-200.fc23.x86_64
gyp ERR! command "node" "/home/lrossetti/.nvm/v0.10.45/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/lrossetti/fh-templates/fh-mbaas-service/node_modules/fh-mbaas-api/node_modules/fh-mbaas-client/node_modules/bunyan/node_modules/dtrace-provider
gyp ERR! node -v v0.10.45
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
gyp: /home/lrossetti/.node-gyp/0.10.45/common.gypi not found (cwd: /home/lrossetti/fh-templates/fh-mbaas-service/node_modules/fh-forms/node_modules/fh-mbaas-client/node_modules/bunyan/node_modules/dtrace-provider) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/lrossetti/.nvm/v0.10.45/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.5.7-200.fc23.x86_64
gyp ERR! command "node" "/home/lrossetti/.nvm/v0.10.45/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/lrossetti/fh-templates/fh-mbaas-service/node_modules/fh-forms/node_modules/fh-mbaas-client/node_modules/bunyan/node_modules/dtrace-provider
gyp ERR! node -v v0.10.45
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing dtrace-provider@0.2.8
npm WARN optional dep failed, continuing dtrace-provider@0.2.8
gyp: /home/lrossetti/.node-gyp/0.10.45/common.gypi not found (cwd: /home/lrossetti/fh-templates/fh-mbaas-service/node_modules/fh-forms/node_modules/mmmagic) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/lrossetti/.nvm/v0.10.45/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.5.7-200.fc23.x86_64
gyp ERR! command "node" "/home/lrossetti/.nvm/v0.10.45/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/lrossetti/fh-templates/fh-mbaas-service/node_modules/fh-forms/node_modules/mmmagic
gyp ERR! node -v v0.10.45
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
gyp: /home/lrossetti/.node-gyp/0.10.45/common.gypi not found (cwd: /home/lrossetti/fh-templates/fh-mbaas-service/node_modules/fh-forms/node_modules/phantom/node_modules/dnode/node_modules/weak) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/lrossetti/.nvm/v0.10.45/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.5.7-200.fc23.x86_64
gyp ERR! command "node" "/home/lrossetti/.nvm/v0.10.45/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/lrossetti/fh-templates/fh-mbaas-service/node_modules/fh-forms/node_modules/phantom/node_modules/dnode/node_modules/weak
gyp ERR! node -v v0.10.45
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing weak@1.0.1
gyp: /home/lrossetti/.node-gyp/0.10.45/common.gypi not found (cwd: /home/lrossetti/fh-templates/fh-mbaas-service/node_modules/fh-forms/node_modules/mongoose-paginate/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/lrossetti/.nvm/v0.10.45/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.5.7-200.fc23.x86_64
gyp ERR! command "node" "/home/lrossetti/.nvm/v0.10.45/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/lrossetti/fh-templates/fh-mbaas-service/node_modules/fh-forms/node_modules/mongoose-paginate/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v0.10.45
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 4.5.7-200.fc23.x86_64
npm ERR! argv "node" "/home/lrossetti/.nvm/v0.10.45/bin/npm" "install" "--production"
npm ERR! node v0.10.45
npm ERR! npm  v2.13.5
npm ERR! code ELIFECYCLE

npm ERR! mmmagic@0.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mmmagic@0.4.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the mmmagic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mmmagic
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lrossetti/fh-templates/fh-mbaas-service/npm-debug.log
```

**Comment by mmurphy** [comment]
@odra what command do you run to see that error?

**Comment by odra** [comment]
@mmurphy  I ran "fh-npm" in the template folder

**Comment by odra** [comment]
I was able to make it work locally by removing the folder $HOME/.node-gyp (I guess something went wrong with gyp at some point).

**Comment by mmurphy** [comment]
works ok locally for me also.  Does that mean it's not a problem?

**Comment by psturc** [comment]
@mmurphy We should merge this after Travis checks succeed. 
@odra At what point exactly did you removed `.node-gyp` folder - right before running `fh-npm` command? I could add this step to the `fh-build` module.

**Comment by odra** [comment]
@psturc removed it before running fh-npm but in theory it should not be a problem in travis because it runs a test inside a container (so it is always a fresh new build)

**Comment by odra** [comment]
@psturc does it work if you remove the preinstall script?

**Comment by psturc** [comment]
@odra You mean without using `fh-build` or without using https://github.com/feedhenry-templates/fh-mbaas-service/pull/42/commits/799f0be9ec71bf814355dc8da65696abcebccd9e? Travis job with running only `npm install` passes. (https://travis-ci.org/psturc/fh-mbaas-service/builds/144733398)

**Comment by odra** [comment]
@psturc @matzew After a bit of testing it seems that node-gyp for node 0.10.x has some problems with openshift images (some modules requires node-gyp because they need to compile something in their build process). It seems to be a common issue.

I did received a warning that the  repository for "registry.access.redhat.com/openshift3/nodejs-010-rhel7" is a legacy one while directly pulling the image from docker (I am not sure if it matters or if there is a newer image around node 0.10).

**Comment by psturc** [comment]
Closing this issue - as explained in RHMAP-8901, `fh-build` is needless for this template.

**Pull request closed without merging**
